check:
  - thoth-precommit
  - thoth-build
  - overlays-build
overlays_dir: overlays
overlays:
  - name: python36
    build:
      base-image: "quay.io/thoth-station/s2i-minimal-notebook:v0.0.7"
      build-stratergy: Source
      registry: "quay.io"
      registry-org: "thoth-station"
      registry-project: "s2i-scipy-notebook"
      registry-secret: "thoth-station-thoth-pusher-secret"

  - name: python38
    build:
      base-image: "quay.io/thoth-station/s2i-minimal-py38-notebook:v0.2.2"
      build-stratergy: Source
      registry: "quay.io"
      registry-org: "thoth-station"
      registry-project: "s2i-scipy-py38-notebook"
      registry-secret: "thoth-station-thoth-pusher-secret"